backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Date Published", name: "date", widget: "datetime" }
      - { label: "SEO Description", name: "description", widget: "text" }
      - { label: "Categories", name: "tags", widget: "list" }
      - { label: "Featured Image", name: "featuredImage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "product"
    label: "Product"
    folder: "content/products"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "product",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "SEO Description", name: "description", widget: "text" }
      - { label: "Store Link", name: "link", widget: "text" }
      - { label: "Subjects", name: "subjects", widget: "list" }
      - { label: "Grade Levels", name: "gradeLevels", widget: "list" }
      - { label: "Resource Types", name: "resourceTypes", widget: "list" }
      - { label: "Standards", name: "standards", widget: "list" }
      - { label: "Featured Image", name: "featuredImage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
